server:
  port: 9000

logging:
  level:
    org.springframework.cloud.consul: DEBUG

---
spring:
#  profiles: docker, development
  cloud:
    consul:
      host: ${CONSUL_PORT:localhost}
#      host: consul-dev
      port: ${CONSUL_PORT:8500}
